# Generated by Django 4.2.3 on 2023-09-09 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_alter_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LibraryApp.address'),
        ),
    ]
