# Generated by Django 4.2.3 on 2023-09-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0004_signupmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpModel',
        ),
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
