# Generated by Django 4.2.3 on 2023-09-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0005_delete_signupmodel_alter_books_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='image',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
    ]
