# Generated by Django 4.2.3 on 2023-09-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0006_reader_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='isbn',
            new_name='book_number',
        ),
    ]
