# Generated by Django 4.2.3 on 2023-09-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0008_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
