# Generated by Django 4.2.3 on 2023-09-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0009_alter_cart_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
