# Generated by Django 4.2.3 on 2023-09-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0011_rental_payment_rental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='pass_reset_code',
            field=models.CharField(max_length=20),
        ),
    ]
